GET http://localhost:5000/api/scores

###

GET http://localhost:5000/api/scores/1

###

POST http://localhost:5000/api/scores
Content-Type: application/json

{
    "name": "Wilder",
    "score": 458
}

###

PUT http://localhost:5000/api/scores/1
Content-Type: application/json

{
    "name": "Arno",
    "score": 300
}

###

DELETE http://localhost:5000/api/scores/2